trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Carahsoft.Calliope
variables:
  BaseVersion: 0.0
  BuildPlatform: AnyCPU
  ProjectName: Carahsoft.Calliope
  Solution: Carahsoft.Calliope.sln
name: $(BaseVersion)$(Rev:.r)
jobs:
- job: Job_1
  displayName: NuGet
  pool:
    vmimage: 'ubuntu-latest'
  variables:
    BuildConfiguration: Release
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: 'Use .NET 8.0.x'
    inputs:
      version: 8.0.x
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: '**/$(ProjectName).sln'
      versioningScheme: byBuildNumber
      arguments: -c $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      projects: '**/$(ProjectName).csproj'
      searchPatternPack: '**/$(ProjectName).csproj'
      versioningScheme: byBuildNumber
      arguments: --no-restore --no-build
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'